Umbetov-Asman-Task-1
fastndead/ui-internship-mocks pull request #1
Opened 2019-10-01 09:18 UTC by fastndead

2019-10-01 11:27 UTC, vadeneev requested changes

2019-10-01 11:27 UTC, vadeneev commented on mock1/public/css/style.css
> +    margin-top: 0;
please fix all indents

2019-10-01 11:27 UTC, vadeneev commented on mock1/public/css/style.css
> +.tile > span{
It is not about BEM, right ?

2019-10-03 07:05 UTC, vovcyan requested changes

2019-10-03 07:05 UTC, vovcyan commented on mock1/public/css/style.css
> +body{
Please format this file

2019-10-03 07:05 UTC, vovcyan commented on mock1/public/css/style.css
> +  background: url(../images/header-background.png) center;
background-image

2019-10-03 07:05 UTC, vovcyan commented on mock1/public/css/style.css
> +  background: url(../images/midpage-background.png) center;
background-image: ...
background-position: center

2019-10-03 07:05 UTC, vovcyan commented on mock1/public/css/style.css
> +
Remove it

2019-10-03 07:05 UTC, vovcyan commented on mock1/public/css/style.css
> +  border-top: 0px;
without px

2019-10-03 07:05 UTC, vovcyan commented on mock1/public/css/style.css
> +  width:100vw;
Format it

2019-10-03 07:05 UTC, vovcyan commented on mock1/public/css/style.css
> +  letter-spacing: 0.6px;
.6px

2019-10-03 07:05 UTC, vovcyan commented on mock1/public/css/style.css
> +  margin-left: 0px;
0

2019-10-03 07:05 UTC, vovcyan commented on mock1/public/css/style.css
> +	transition: .1s;
Remove spaces

2019-10-03 07:05 UTC, vovcyan commented on mock1/public/css/style.css
> +  opacity: 0.5;
.5

2019-10-03 07:05 UTC, vovcyan commented on mock1/public/css/style.css
> +.footer__logo{
Format it

2019-10-03 07:05 UTC, vovcyan commented on mock1/public/css/style.css
> +}
Please add media for vertical iPad

2019-10-03 07:05 UTC, vovcyan commented on mock1/public/index.html
> +    <div class="wrapper" id="firstSection">
Please do not use id at all

2019-10-03 07:05 UTC, vovcyan commented on mock1/public/index.html
> +        <h2 class="text text_white text_heading_second  text_heading_second_white"><span>Services</span></h2>
Please separate it into 2 lines

2019-10-03 07:05 UTC, vovcyan commented on mock1/public/index.html
> +        <h2 class="text text_heading_second"><span>What we do</span></h2>
The same

2019-10-03 07:05 UTC, vovcyan commented on mock1/public/index.html
> +         <img class="container__icon" src="/public/images/design-icon.png" alt="design-icon">
Please change alt attribute

2019-10-03 07:05 UTC, vovcyan commented on mock1/public/index.html
> +         <img class="container__icon" src="/public/images/development-icon.png" alt="development-icon">
The same

2019-10-03 07:05 UTC, vovcyan commented on mock1/public/index.html
> + interaction and visual design and user experience testing.
Please format text

2019-10-03 07:05 UTC, vovcyan commented on mock1/public/index.html
> +            <span class="tile__label">topworkz</span>
Why 3 spaces there?

2019-10-03 07:05 UTC, vovcyan commented on mock1/public/index.html
> +
Remove it

2019-10-03 07:05 UTC, vovcyan commented on mock1/public/index.html
> +        <h2 class="text text_heading_second"><span>Contact us</span></h2>
The same

2019-10-03 07:05 UTC, vovcyan commented on mock1/public/index.html
> +
Remove it

2019-10-04 11:19 UTC, vadeneev requested changes

2019-10-04 11:19 UTC, vadeneev commented on mock1/public/css/style.css
> +    ;
🐘

2019-10-04 11:19 UTC, vadeneev commented on mock1/public/css/style.css
> +    width: 100.5%;
so weird, is that required ?

2019-10-04 11:19 UTC, vadeneev commented on mock1/public/css/style.css
> +    display: table-cell;
really ? Why do we need that ?

2019-10-04 11:19 UTC, vadeneev commented on mock1/public/css/style.css
> +footer>.container {
It is not allowed to use element selector in BEM

2019-10-04 12:17 UTC, vadeneev approved these changes

2019-10-04 13:11 UTC, vovcyan approved these changes

2019-10-04 13:11 UTC, merged